baseURL = '/'
languageCode = 'en-us'
title = 'Hack it!'
theme = "mainroad"
disqusShortname = "xinlianglyu" # Enable Disqus comments by entering your Disqus shortname

[Author] # Used in authorbox
  name = "Xinliang Lyu"
  # bio = ""
  # avatar = "img/avatar.png"

[Params]
  description = "Amazing stuffs" # Site description. Used in meta description
  copyright = "Xinliang Lyu" # Footer copyright holder, otherwise will use site title
  post_meta = ["author", "date", "wordcount"]
  dateformat = "2006-01-02" # Change the format of dates

[Params.logo]
  # image = "img/placeholder.png" # Logo image. Path relative to "static"
  image = "img/the-matrix.jpg" # Logo image. Path relative to "static"
  subtitle = "Amazing stuffs" # Logo subtitle

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["social"]

[Params.widgets.social]
  cached = true # activate cache if true
  # Enable parts of social widget
  github = "brucelyu"
  email = "lyu@xllyu.org"

[[Params.widgets.social.custom]]
  title = "My main website"
  url = "https://xllyu.org"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 20
[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 30
